### ISSUE TITLE
Cannot get to work

### ISSUE THREAD

**Issue by Tatsh** [mbird1258/Audio-Decomposition#5]
Every file I try to use whether it's FLAC or WAV gives me an error like this:

```
 $ python Main.py PlayBack

iteration:   1760/1761
1 - 0/36 | 2 - 0/36

B2

C3

Db3

D3

Eb3

E3

F3
/home/tatsh/dev/Audio-Decomposition/Main.py:184: RuntimeWarning: invalid value encountered in cast
  A, B, C, D = np.floor(keypoints/SliceInterval).astype(int)
        Piano.ff.F3.pkl
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:227: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:184: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:219: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:149: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret / rcount
Traceback (most recent call last):
  File "/home/tatsh/dev/Audio-Decomposition/Main.py", line 364, in <module>
    out1.extend(GetEnvelopeCosts(slice, ind*WindowSize))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tatsh/dev/Audio-Decomposition/Main.py", line 254, in GetEnvelopeCosts
    Y = np.concatenate((norm(attack[-len(WaveAttack):]), norm(sustain[:len(WaveSustain[:-int(samplerate*0.1)][:samplerate])])), axis=None)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tatsh/dev/Audio-Decomposition/Main.py", line 247, in <lambda>
    norm = lambda x: (x-np.mean(x))/np.std(x)
                                    ^^^^^^^^^
  File "/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py", line 4111, in std
    return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py", line 227, in _std
    ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tatsh/dev/Audio-Decomposition/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py", line 184, in _var
    arrmean = um.true_divide(arrmean, div, out=arrmean,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ZeroDivisionError: division by zero
```

**Comment by mbird1258** [comment]
I’m not entirely sure what’s causing the issue, since it’s probably instrument specific, but this should be caused by WaveSustain being shorter than expected. A little bandage fix is to change norm to return [] if len(x) == 0. 

The underlying problem causing this should be the ADSR boundaries calculated in the ProcessInstruments.py being too close or overlapping with each other, you can run print(A, B, C, D) in line 185 to make sure that everything is alright with the instrument sample files, since it should be that D > C > B > A with at least a small distance between each. Another way to check this is to see the result of the following few lines of code added after line 185. 

print("\n"*2)
for i in [a, b, c, d]:
    plt.plot(envelope)
    plt.plot([i, i], [0, np.max(envelope)]
    plt.show()

plt.plot(envelope)
for i in [a, b, c, d]:
    plt.plot([i, i], [0, np.max(envelope)]
plt.show()
print("\n"*2)

This should show you the envelope of the instrument sample file that it’s processing, and each of the cutoff boundaries one by one. I’d suggest that you run it in a jupyter notebook with %matplotlib inline, so that you can see all the graphs together and it runs faster. You can also skip directly to time index 1760 and Piano.ff.F3 so that you can get directly to the issue. (or time index 1759 to see how it should work and see what changed in time index 1760 graphs)
